---

name: Quality workflow
run-name: "Workflow: ${{ github.workflow }} on event: ${{ github.event_name }}"
on: 
    push:
        branches-ignore: 'main'
    pull_request:

jobs:
    build :
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-Java@v3
              with:
                java-version: '17'
                distribution: 'adopt'
            - name: Build with Maven
              run: mvn -B package --file pom.xml

                                                