---

name: Quality workflow
run-name: "Workflow: ${{ github.workflow }} on event: ${{ github.event_name }}"
on: 
    pull_request:

jobs:
    build :
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-Java@v3
              with:
                java-version: '17'
                distribution: 'adopt'
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: SonarCloud Scan
              run: mvn sonar:sonar -Dsonar.projectKey=benauca-webgoat-test -Dsonar.organization=benauca -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.exclusions=**/target/**,**/node_modules/**,**/src/test/** -Dsonar.branch=main
